environment:

  matrix:
    - PYTHON_VERSION: 3.5
      TOXENV: py35-test
    - PYTHON_VERSION: 3.6
      TOXENV: py36-test
    - PYTHON_VERSION: 3.7
      TOXENV: py37-test

install:
  - pip install tox
  - pip install coveralls
  - pip freeze

build: off

test_script:
  - tox -e %TOXENV% -- src tests README.rst docs\notebooks\01_example_simple_state_to_state.ipynb docs\notebooks\02_example_lambda_system_rwa_complex_pulse.ipynb docs\notebooks\03_example_lambda_system_rwa_non_hermitian.ipynb
