# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-test
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.7
      env: TOXENV=py37-test
install:
  - pip install tox
  - pip install coveralls
  - pip freeze
script:
  - tox
after_success:
  - coveralls
